#.travis.yml

language: node_js
node_js:
  - "8.9"

before_script:
  - npm install

script:
  - npm run lint
  - npm run test -- --browsers PhantomJS --watch=false
  - npm run build -- --prod --aot --env prod

after_success:
  - if [[ $TRAVIS_BRANCH =~ ^master$ ]] ; then
      export TARGET=prod ;
    elif [[ $TRAVIS_BRANCH =~ ^rc-[0-9].[0-9].[0-9]$ ]] ; then
      export TARGET=next ;
    elif [[ $TRAVIS_BRANCH =~ ^develop$ ]] ; then
      export TARGET=devl ;
    fi
  - if [[ ! -z $TARGET ]] ; then
      npm install -g firebase-tools ;
      firebase deploy --only hosting:${TARGET} --token=${FIREBASE_API_TOKEN} ;
    fi

notifications:
  email:
    on_failure: change
    on_success: change

env:
  global:
    #FIREBASE_API_TOKEN
    - secure: FN7ghlAtlysyJsl41fplhI9ykfio8k3BVE6P0SiEpFoxLPhUayPLMEGky0XWSCfqsMaZuLA+09fa0QUo+UlwOjG6ruDLlLfCVAhLlxHEswwAR//jK3IptJAMgqrTbkb0pNe068YzTbS4mZ1WmUFXGuRQaEAyv0shiSyLuK8YcVMxoNmDANBEYdH5n+d2eiVcx1wJx+C13PigUOfj4joISJ+qCyAiaRdPl4FVty6XCC1AlmP2oE97DbM/CmSUXXlBjsKC0m8F698O6vkH+fCNYoDk7uO7ESPZCjTn/xrxURAggcxWuXVSvcU5IRl60YcU/gThKc8cLiTQ4YnZsNXFGVkWU2Pye8y2Fndc9b60Et7TXpGsfC9zjz1modjGxLwFsBy6R25Fsr3aH9aeNSCKEKxLGzufvaC8sGB9bhLh840d0EboxJWQ8iyyxiU7jIyIr8y8nj5R0hX7Wvfp7Wj6fOoGmQ/vOHjxo+TKv0owU3hrVOyy6ig/7ffX8Q3+rIxRSfg8hE8YiIOFs7bptY+15ZK2FMswvs34pa7nG7DmFpfhypx5Ddp0K5nlC72ZzwNGGoAewQLeprEDBtUegMc7oifsrCyY1ZfX/D9sAwWgYsMN6T8xkl/DYGWvSmMBRW+v5sUmHIDeYk+KBrpOWr3hYkBQP7yGbV5n0UETYt0ZtGw=